remote_theme: "mmistakes/minimal-mistakes@4.18.1"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

locale: "en-US"
title                    : "IT South at AFRY"
title_separator          : "-"
subtitle                 : "The blog"
words_per_minute         : 200
breadcrumbs: true  # disabled by default
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
#search_provider          : algolia # lunr (default), algolia
#algolia:
#  application_id         : QB6HVGBSBA # YOUR_APPLICATION_ID
#  index_name             : minimal_mistakes # YOUR_INDEX_NAME
#  search_only_api_key    : 9d5014e5bbc77372547bce778dfa5663 # YOUR_SEARCH_ONLY_API_KEY
#  powered_by             : true # true (default), false
#  files_to_exclude:
#    - _posts/2017-11-28-post-exclude-search.md

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Reading Files
include:
  - .htaccess
  - _pages
  - tipsrundan
  - lunches

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # tipsrundan
  - scope:
      path: ""
      type: tipsrundan
    values:
      layout: single


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
